services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/app
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf

  app-php82:
    build: php82
    volumes:
      - ../:/var/www/app
    working_dir: /var/www/app
    ports:
      - 9074:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  minha-rede:
    ipam:
      config:
        - subnet: 172.20.0.0/16